[build]
  command = "rm -rf flutter && git clone https://github.com/flutter/flutter.git --branch stable --depth 1 && export PATH=\"$PATH:`pwd`/flutter/bin\" && flutter pub get && flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200